### ISSUE TITLE
Splunk 7.x Support

### ISSUE THREAD

**Issue by austintking** [Cisco-AMP/amp4e_splunk_cim_add_on#2]
Hello,

We are currently running Splunk 7.x. When installing the TA, we are unable to retrieve the inputs. When we open the app, the first tab "inputs" just says "retrieving inputs" and never does so successfully. 

We tested this on Splunk 6.x and it appears to work. We believe that this is a Splunk 7.x related bug with the application. 

Thank you.

**Comment by samsonnguyen** [comment]
This is an issue on the Events input app - https://github.com/Cisco-AMP/amp4e_splunk_events_input/issues/2

Closing
