### ISSUE TITLE
Cisco AMP for Endpoints CIM Add-on configuration

### ISSUE THREAD

**Issue by ahmadjabr** [Cisco-AMP/amp4e_splunk_cim_add_on#3]
what do you mean by "Cisco AMP for Endpoints CIM Add-on configuration" 
 AMP host :???????

**Comment by samsonnguyen** [comment]
Hi,

This value should be the URL used to access the AMP console. Depending on your region this will be:

Region | AMP host
--- | ---
NA | console.amp.cisco.com
EU | console.eu.amp.cisco.com
APJC | console.apjc.amp.cisco.com
